### ISSUE TITLE
map: invalid keys sort

### ISSUE THREAD

**Issue by wI2L** [segmentio/encoding#15]
@achille-roussel Hello,

As I was reading the code of the package, I noticed the `sortKeys` function that is created based on the map key type to encode, and saw that you sort on the `reflect.Value` value rather than the string representation of the key.

I was perplex to find that as an optin functionality, since the package aims to be compliant with the standard library, unless I misunderstood the README.

The following example shows that the output is different when using a map with keys of type `int`: https://play.golang.org/p/1ddbUssdbaf

The only reference to a map with keys of signed/unsigned-integer kind I could find in the tests is at https://github.com/segmentio/encoding/blob/bc545e97dc873711de072cb3246241637958745f/json/json_test.go#L190 but the keys are already lexicographicaly sorted.

**Comment by achille-roussel** [comment]
@wI2L Thanks for reporting the issue! And you're correct, this seems like a mistake.

Would you be available to submit a fix? Otherwise I'll take a look at it sometimes this weekend.

**Comment by wI2L** [comment]
@achille-roussel Sure, I'll send a PR tomorrow, this is a quickfix.

**Comment by ofek** [comment]
Any update?

**Comment by achille-roussel** [comment]
I'm working on it.
