### ISSUE TITLE
Error messages could be improved

### ISSUE THREAD

**Issue by frioux** [segmentio/encoding#40]
This demonstrates the issue: https://play.golang.org/p/SwaihNVSqAl

I personally would be fine with the field being set to `a` or `A`, but `a.` is pretty clearly wrong.

**Comment by achille-roussel** [comment]
Thanks for reporting!

We always welcome contributions, would you be available to submit a patch to address this issue?

**Comment by frioux** [comment]
Absolutely. I wanted to make sure the group agreed with the intended changes before submitting a patch. My default would be to make it match the error that `encoding/json` returns.

**Comment by achille-roussel** [comment]
At the time we were writing this package the errors reported by `encoding/json` weren't really helpful, so we tried to improve it, but it seems that goal didn't really materialize :)

Matching the `encoding/json` behavior sounds good, although it may be hard to achieve long term as there is no guarantee on the format of these errors, the amount of testing and the maintenance cost to keep up with changes may not be worth it, I think we tried to match the error types but did not really aim for the error messages to be the same.

Do what you think is right 👍

**Comment by frioux** [comment]
So I made a little test to compare the values of various mistyped parses to compare `encoding/json` and this lib.  Here are the results:

```
--- FAIL: TestDecodeErrors (0.00s)
    --- FAIL: TestDecodeErrors/0 (0.00s)
        errors_test.go:70: value doesn't match encoding/json, got "\"1}\"", expected "number"
        errors_test.go:73: offset doesn't match encoding/json, got 0, expected 9
        errors_test.go:76: struct doesn't match encoding/json, got "json.example", expected "example"
        errors_test.go:79: field incorrect, got "name.", expected "Name"
        errors_test.go:82: representation doesn't match encoding/json, got "json: cannot unmarshal \"1}\" into Go struct field json.example.name. of type string", expected "json: cannot unmarshal number into Go struct field example.Name of type string"
    --- FAIL: TestDecodeErrors/1 (0.00s)
        errors_test.go:70: value doesn't match encoding/json, got "\"1}}\"", expected "number"
        errors_test.go:73: offset doesn't match encoding/json, got 0, expected 24
        errors_test.go:76: struct doesn't match encoding/json, got "json.examplejson.Inner", expected "Inner"
        errors_test.go:79: field incorrect, got "inner.innername.", expected "Inner.InnerName"
        errors_test.go:82: representation doesn't match encoding/json, got "json: cannot unmarshal \"1}}\" into Go struct field json.examplejson.Inner.inner.innername. of type string", expected "json: cannot unmarshal number into Go struct field Inner.Inner.InnerName of type string"
    --- FAIL: TestDecodeErrors/2 (0.00s)
        errors_test.go:70: value doesn't match encoding/json, got "\"1}\"", expected "number"
        errors_test.go:73: offset doesn't match encoding/json, got 0, expected 8
        errors_test.go:76: struct doesn't match encoding/json, got "json.example", expected "example"
        errors_test.go:79: field incorrect, got "map.", expected "Map"
        errors_test.go:82: representation doesn't match encoding/json, got "json: cannot unmarshal \"1}\" into Go struct field json.example.map. of type map[string]json.MapStruct", expected "json: cannot unmarshal number into Go struct field example.Map of type map[string]json.MapStruct"
    --- FAIL: TestDecodeErrors/3 (0.00s)
        errors_test.go:70: value doesn't match encoding/json, got "\"1}}\"", expected "number"
        errors_test.go:73: offset doesn't match encoding/json, got 0, expected 19
        errors_test.go:76: struct doesn't match encoding/json, got "json.examplemap[string]json.MapStruct{}", expected "example"
        errors_test.go:79: field incorrect, got "map.mapname.", expected "Map"
        errors_test.go:82: representation doesn't match encoding/json, got "json: cannot unmarshal \"1}}\" into Go struct field json.examplemap[string]json.MapStruct{}.map.mapname. of type json.MapStruct", expected "json: cannot unmarshal number into Go struct field example.Map of type json.MapStruct"
    --- FAIL: TestDecodeErrors/4 (0.00s)
        errors_test.go:70: value doesn't match encoding/json, got "\"1}\"", expected "number"
        errors_test.go:73: offset doesn't match encoding/json, got 0, expected 10
        errors_test.go:76: struct doesn't match encoding/json, got "json.example", expected "example"
        errors_test.go:79: field incorrect, got "slice.", expected "Slice"
        errors_test.go:82: representation doesn't match encoding/json, got "json: cannot unmarshal \"1}\" into Go struct field json.example.slice. of type []json.SliceStruct", expected "json: cannot unmarshal number into Go struct field example.Slice of type []json.SliceStruct"
    --- FAIL: TestDecodeErrors/5 (0.00s)
        errors_test.go:70: value doesn't match encoding/json, got "\"1}]}\"", expected "number"
        errors_test.go:73: offset doesn't match encoding/json, got 0, expected 24
        errors_test.go:76: struct doesn't match encoding/json, got "json.example[]json.SliceStructjson.SliceStruct", expected "SliceStruct"
        errors_test.go:79: field incorrect, got "slice.0.slicename.", expected "Slice.SliceName"
        errors_test.go:82: representation doesn't match encoding/json, got "json: cannot unmarshal \"1}]}\" into Go struct field json.example[]json.SliceStructjson.SliceStruct.slice.0.slicename. of type string", expected "json: cannot unmarshal number into Go struct field SliceStruct.Slice.SliceName of type string"
```

The only thing I intended to fix was the Field value, though I think Field and Struct are clearly related so I would be willing to call them both worth fixing.  Here are the issues with `encoding/json`:

 * error context is not as good, just says the type that was wrong, not a fragment like this lib
 * no extra context on nested types; the inclusion of the package and enclosing types by this library is clearly useful

Here are the issues with `github.com/segmentio/encoding`:

 * All fields get a silly trailing dot.  Likely easy to fix.
 * fields are in terms of json, not go fieldnames.  I suspect this is easy to fix.
 * complex types end up messy or inscrutable (eg `json.example[]json.SliceStructjson.SliceStruct`)

---

My plan is to remove the trailing dot, correct fields to match Go fields, not json fields, and *maybe* clean up the complex types.  The only thing that makes me nervous about this is that if anyone is depending on these strings (I am sure some people do) their error checking code will silently stop working.  I would be willing to add a new field or fields to the error struct but that would imply no longer making a type alias, which I'm sure would break yet more code.

Is it worth fixing this and causing a break in compatibility?

---

(and for posterity, the actual test:

```golang
package json

import (
	"encoding/json"
	"errors"
	"strconv"
	"strings"
	"testing"
)

func TestDecodeErrors(t *testing.T) {
	type Test struct{ in, err string }
	type Inner struct {
		InnerName string
	}
	type MapStruct struct {
		MapName string
	}
	type SliceStruct struct {
		SliceName string
	}
	type example struct {
		Name string

		Inner Inner

		Map map[string]MapStruct

		Slice []SliceStruct
	}
	tests := []Test{
		0: {`{"name":1}`, ""},
		1: {`{"inner":{"innername": 1}}`, ""},

		2: {`{"map":1}`, ""},
		3: {`{"map":{"mapname":1}}`, ""},

		4: {`{"slice":1}`, ""},
		5: {`{"slice":[{"slicename":1}]}`, ""},
	}

	for i, tt := range tests {
		t.Run(strconv.Itoa(i), func(t *testing.T) {
			var dest example
			d := NewDecoder(strings.NewReader(tt.in))
			err := d.Decode(&dest)
			if err == nil {
				t.Error("expected an error but got none")
				return
			}
			typedErr := &UnmarshalTypeError{}
			if !errors.As(err, &typedErr) {
				t.Errorf("expected UnmarshalTypeError, got %T", err)
				return
			}
			d2 := json.NewDecoder(strings.NewReader(tt.in))
			expectedErr := d2.Decode(&dest)
			if expectedErr == nil {
				t.Error("expected an error but got none")
				return
			}

			typedExpectedErr := &json.UnmarshalTypeError{}
			if !errors.As(expectedErr, &typedExpectedErr) {
				t.Errorf("expected UnmarshalTypeError, got %T", expectedErr)
				return
			}

			if typedErr.Value != typedExpectedErr.Value {
				t.Logf("value doesn't match encoding/json, got %q, expected %q", typedErr.Value, typedExpectedErr.Value)
			}
			if typedErr.Offset != typedExpectedErr.Offset {
				t.Logf("offset doesn't match encoding/json, got %d, expected %d", typedErr.Offset, typedExpectedErr.Offset)
			}
			if typedErr.Struct != typedExpectedErr.Struct {
				t.Logf("struct doesn't match encoding/json, got %q, expected %q", typedErr.Struct, typedExpectedErr.Struct)
			}
			if typedErr.Field != typedExpectedErr.Field {
				t.Errorf("field incorrect, got %q, expected %q", typedErr.Field, typedExpectedErr.Field)
			}
			if typedErr.Error() != typedExpectedErr.Error() {
				t.Logf("representation doesn't match encoding/json, got %q, expected %q", typedErr, typedExpectedErr)
			}
		})
	}
}
```

**Comment by achille-roussel** [comment]
> My plan is to remove the trailing dot, correct fields to match Go fields, not json fields, and maybe clean up the complex types.

This plan sounds great, thanks for the thorough analysis and reporting 👍  The choice of using json field names vs Go's was not really thought out, if experience tells us that reporting the Go field name is more informative then let's change it.

> The only thing that makes me nervous about this is that if anyone is depending on these strings

I don't think this is a promise we made with this package, and the effort we've put into using exported error types that programs can test their errors against should have allowed developers to avoid relying on the raw error messages. One case to watch out for would be places where errors are constructed via `fmt.Errorf` or `errors.New` instead of using one of the exported error types, but I don't think the changes we're discussing here overlap with these.

Go for it!

**Comment by achille-roussel** [comment]
As a side note, we can tag the next release v0.2.0 to represent that the output of the package is being changed under some conditions.

**Comment by frioux** [comment]
Just to be clear, you are correct that people can check against fields directly, but because this changes the values of such fields, people will still have to change code to match the new convention of using Go field names, rather than json field names.

**Comment by achille-roussel** [comment]
Ah! I understand your point better.

I still feel like the content of error messages is beyond the backward compatibility promises of this package, so I wouldn't want to prevent improvements in this area on the assumption that programs would have chosen to take a dependency on values that were not documented as offering any stability.

This is still an opt-in change, programs using go modules will not automatically receive the new version on their next build. Clear documentation on the changes we are making + tagging v0.2.0 seem like enough guidance for developers to adopt the new version.
