### ISSUE TITLE
JSON tests fail on Go 1.13

### ISSUE THREAD

**Issue by Fenny** [segmentio/encoding#43]
Hi @achille-roussel, first I want to say you did an awesome job with this library 💯

According to the [go.mod](https://github.com/segmentio/encoding/blob/master/go.mod#L3) file this package should be compatible with `Go 1.13`, but when I run `go test ./... -v -race` on this version it seems to fail. Should this be correct since we are only testing on `Go 1.14` <https://github.com/segmentio/encoding/blob/master/.circleci/config.yml#L5>?
```go
=== RUN   TestCompact
--- FAIL: TestCompact (0.00s)
##[error]    golang_scanner_test.go:73: Compact(`{"":"<>&  "}`) = `{"":"<>&\u2028\u2029"}`, want original
##[error]    golang_scanner_test.go:81: Compact("{\n\t\"\": \"<>&\u2028\u2029\"\n}") = `{"":"<>&\u2028\u2029"}`, want `{"":"<>&  "}`
=== RUN   TestCompactSeparators
--- FAIL: TestCompactSeparators (0.00s)
##[error]    golang_scanner_test.go:100: Compact("{\"\u2028\": 1}") = "{\"\\u2028\":1}", want "{\"\u2028\":1}"
##[error]    golang_scanner_test.go:100: Compact("{\"\u2029\" :2}") = "{\"\\u2029\":2}", want "{\"\u2029\":2}"

=== RUN   TestGithubIssue11
--- PASS: TestGithubIssue11 (0.00s)
##[error]    json_test.go:1228: json: unsupported value: NaN
=== RUN   TestGithubIssue13
--- PASS: TestGithubIssue13 (0.00s)
##[error]    json_test.go:1249: {"Stringer":null,"MyInt":0}

--- PASS: TestDecodeLines (0.00s)
    --- PASS: TestDecodeLines/bare_object (0.00s)
    --- PASS: TestDecodeLines/multiple_objects_on_one_line (0.00s)
    --- PASS: TestDecodeLines/object_spanning_multiple_lines (0.00s)
    --- PASS: TestDecodeLines/trailing_newline (0.00s)
    --- PASS: TestDecodeLines/multiple_trailing_newlines (0.00s)
    --- PASS: TestDecodeLines/blank_lines (0.00s)
    --- PASS: TestDecodeLines/no_trailing_newline (0.00s)
    --- PASS: TestDecodeLines/leading_whitespace (0.00s)
    --- PASS: TestDecodeLines/one_object,_multiple_reads (0.00s)
    --- PASS: TestDecodeLines/one_object_+_EOF (0.00s)
    --- PASS: TestDecodeLines/leading_whitespace_+_EOF (0.00s)
    --- PASS: TestDecodeLines/multiple_objects_+_EOF (0.00s)
    --- PASS: TestDecodeLines/one_object_+_multiple_reads_+_EOF (0.00s)
    --- PASS: TestDecodeLines/multiple_objects_+_multiple_reads_+_EOF (0.00s)
    --- PASS: TestDecodeLines/unmarshal_error_while_decoding (0.00s)
##[error]        json_test.go:735: unmarshal error json: cannot unmarshal "42}" into Go struct field json.obj.Good. of type bool
    --- PASS: TestDecodeLines/unmarshal_error_while_decoding_last_object (0.00s)
##[error]        json_test.go:735: unmarshal error json: cannot unmarshal "42}" into Go struct field json.obj.Good. of type bool

**Comment by abraithwaite** [comment]
This is a result of this change in Go1.14:

https://golang.org/doc/go1.14#encoding/json

Unfortunately, Go1.13 is now deprecated with the release of Go1.15.  I could be wrong, but I believe we're taking the same approach around deprecation timelines, so (understanding I haven't read the code for this issue) I think it's unlikely to be fixed.

Is there something keeping you on Go1.13 in particular?

**Comment by achille-roussel** [comment]
The reason the tests failed is because there was a behavior change in `encoding/json` in Go 1.14 that we ported to this project (see https://github.com/segmentio/encoding/pull/34).

The path forward should be to update `go.mod` to require Go 1.14 I think, if you want to remain on Go 1.13 you should use v0.1.10 (although that may not be a great option since it means giving up on some bug fixes).

**Comment by Fenny** [comment]
There is no particular reason to use `1.13`, but if it means it's not cross-compatible with other projects that run on `1.11` or higher for example. I think we should adjust the go.mod, I can make a PR for this.
