### ISSUE TITLE
json.UnmarshalTypeError appends extra dot

### ISSUE THREAD

**Issue by kiyonlin** [segmentio/encoding#56]
Hey, guys! We met an issue(gofiber/fiber#1012).  And it turns out that `json.UnmarshalTypeError` doesn't have same behavior with standard `"encoding/json"`.

Here is the reproduction:

With `"encoding/json"` [playgrould](https://play.golang.org/p/HDMniI29SkY)
```go
package main

import (
	"encoding/json"
	"fmt"
)

type Cc struct {
	Id   int    `json:"id" xml:"id" form:"id"`
	Name string `json:"name" xml:"name" form:"name"`
}

func main() {
	var s Cc
	err := json.Unmarshal([]byte(`{ "id":"123" }`), &s)
	switch err.(type) {
	case *json.UnmarshalTypeError:
		unmarshalTypeError := err.(*json.UnmarshalTypeError)
		fmt.Printf("%v\n", unmarshalTypeError.Field)
	}
}
```

Output is `id`

With `"github.com/segmentio/encoding/json"` [playground](https://play.golang.org/p/KlMmiYoLeds)
```go
package main

import (
	"github.com/segmentio/encoding/json"
	"fmt"
)

type Cc struct {
	Id   int    `json:"id" xml:"id" form:"id"`
	Name string `json:"name" xml:"name" form:"name"`
}

func main() {
	var s Cc
	err := json.Unmarshal([]byte(`{ "id":"123" }`), &s)
	switch err.(type) {
	case *json.UnmarshalTypeError:
		unmarshalTypeError := err.(*json.UnmarshalTypeError)
		fmt.Printf("%v\n", unmarshalTypeError.Field)
	}
}
```

Output is `id.`

Edit:
I'm sorry, it seems to be kind of duplicated with #40

**Comment by achille-roussel** [comment]
Thanks for reporting @kiyonlin!

This looks similar to https://github.com/segmentio/encoding/issues/40, which we had an attempt to address in https://github.com/segmentio/encoding/pull/51 but it looks like the original contributor may have had to drop the effort.

Would you have a few cycles to push that pull request through the finish line?

**Comment by Fenny** [comment]
@achille-roussel could you review https://github.com/segmentio/encoding/pull/57

**Comment by achille-roussel** [comment]
I tagged v0.2.4 with the fix.
