### ISSUE TITLE
SIGILL on v0.2.10 and above on older hardware due to #66

### ISSUE THREAD

**Issue by aaron42net** [segmentio/encoding#79]
On an x86-64 machine that does not support AVX2 (introduced in 2013), segmentio/encoding/ascii now crashes with:

```
SIGILL: illegal instruction
PC=0x6cf18b m=7 sigcode=2
instruction bytes: 0xc4 0xe2 0x7d 0x59 0xd0 0xc4 0xe2 0x7d 0x59 0xd9 0x48 0x83 0xf9 0x4 0xf 0x8c
goroutine 458 [running]:
github.com/segmentio/encoding/ascii.validPrint16(0xc00134e8ab, 0x2, 0x1)
        github.com/segmentio/encoding@v0.2.10/ascii/valid_amd64.s:23 +0x4b fp=0xc00311ee48 sp=0xc00311ee40 pc=0x6cf18b
```

Line 23 of valid_amd64.s is "VPBROADCASTQ X0, Y2".

This is due to the use of AVX2 instructions on machines that don't support them; there's no guard here checking CPUID to fall back to older behavior that I can see.  Can that be added?

Or if the intent to kill off support for x86-64 hardware produced between 2003 and 2013, please add this to the release notes and README.

Thanks!
-- Aaron

**Comment by achille-roussel** [comment]
Thanks for the report!

I'll add a check for CPU capabilities to default to non-AVX if it isn't available 👍

**Comment by achille-roussel** [comment]
@aaron42net if you don't mind checking that the latest version is not causing SIGKILL anymore (I don't have access to hardware without AVX2 to verify unfortunately).

**Comment by aaron42net** [comment]
Testing out  v0.2.13, that seems to work fine on older hardware.  Thanks for the fast turnaround!
