### ISSUE TITLE
unable to run benchmarks

### ISSUE THREAD

**Issue by vrischmann** [segmentio/encoding#8]
I'm attempting to run [bench-simple](https://github.com/segmentio/encoding/blob/master/Makefile#L21-L26) but for some reason it's not producing any output.
```
$ make bench-simple
GO111MODULE=off go install golang.org/x/tools/cmd/benchcmp
PASS
ok      github.com/segmentio/encoding/json      17.447s
PASS
ok      github.com/segmentio/encoding/json      18.226s
benchcmp encoding-json.txt segmentio-encoding-json.txt
benchcmp: no repeated benchmarks
make: *** [Makefile:26: bench-simple] Error 1
```

if I replace `-bench /codeResponse` with `-bench BenchmarkMarshal/int` for example it works fine, I get the benchmark output and benchcmp works too.

**Comment by achille-roussel** [comment]
Hello @vrischmann, do you mind sharing which version of Go you're using?

**Comment by vrischmann** [comment]
I'm using `go version go1.13.4 linux/amd64`. I've installed `go version devel +ae2e2446` with [gotip](https://godoc.org/golang.org/dl/gotip) and with this version it works fine.

**Comment by jnjackins** [comment]
This is what I get with go1.13.5, without changing the `-bench /codeResponse` flag:

```
$ go test -v -run '^$$' -bench /codeResponse -benchmem -benchtime 3s -cpu 1 ./json -package encoding/json | tee encoding-json.txt
goos: darwin
goarch: amd64
pkg: github.com/segmentio/encoding/json
BenchmarkMarshal/*json.codeResponse2         	     558	   6911451 ns/op	 280.76 MB/s	       0 B/op	       0 allocs/op
BenchmarkUnmarshal/*json.codeResponse2       	     128	  28811230 ns/op	  67.35 MB/s	 1851505 B/op	   76372 allocs/op
PASS
ok  	github.com/segmentio/encoding/json	43.216s
```

Also it seems that tests are running in your case (judging by the 18s run times, with no benchmarks) but they should not be. What happens when you run the command directly in bash vs via make?

**Comment by vrischmann** [comment]
Same result while running go test directly.
```
$ go test -v -run '^$$' -bench /codeResponse -benchmem -benchtime 3s -cpu 1 ./json -package encoding/json | tee encoding-json.txt
PASS
ok      github.com/segmentio/encoding/json      28.426s
```

but I think I figured it out: I'm using the go distribution from Fedora and apparently they broke something, because it works fine if I run the benchmarks using the distribution from golang.org, both on my Fedora system and on a Debian vm.

So I'm going to close this then.
